<template>
  <div class="card">
    <img :src="qr.dataImage" class="card-img-top" :alt="qrCodeId" />
    <div class="card-body">
      <h5 class="card-title">ID:{{ qrCodeId }}</h5>
      <p class="card-text">
        This card generated by {{ qr.username }} with number {{ qr.number }} and type
        <i style="color: #dc3545"> {{ convertedType }}. </i>
      </p>
      <a :download="qrCodeId" :href="qr.dataImage">Download this QR Code only.</a>
    </div>
  </div>
</template>
<script setup lang="ts">
import { defineProps, computed } from 'vue';
import { QRGenerateData, QRVerifyData } from '@/types/QRCode';

const props = defineProps({
  qr: {
    type: Object as () => QRGenerateData,
    required: true,
  },
});

const typesConvert = {
  0: 'Free',
  1: 'Cut in',
  2: 'Cut in and free',
};

// create a computed property
const qrCodeId = computed(() => props.qr.username + props.qr.number);
const convertedType = computed(() => typesConvert[props.qr.type as keyof typeof typesConvert]);
</script>
<style scoped lang="scss"></style>
